-- SQL query for extracting data from Postgress 

SELECT  
  FILM.FILM_ID,
  TITLE,
  DESCRIPTION,
  RELEASE_YEAR,
  LANGUAGE_ID,
  RENTAL_DURATION,
  RENTAL_RATE,
  LENGTH,
  REPLACEMENT_COST,
  RATING,
  FILM.LAST_UPDATE,
  FILM_ACTOR.ACTOR_ID,
  ACTOR.FIRST_NAME,
  ACTOR.LAST_NAME
FROM
    FILM 
LEFT JOIN
    FILM_ACTOR
ON  FILM.FILM_ID = FILM_ACTOR.FILM_ID
LEFT JOIN 
    ACTOR
ON FILM_ACTOR.ACTOR_ID = ACTOR.ACTOR_ID; 
